language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
install:
  - sudo python setup.py install
script:
  - pytest --cov
after_success:
  - codecov
