language: python
python:
  - "3.6"
before_install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install scipy
  - pip install tqdm
install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install"
script:
  - pytest --cov AnnoDomini
after_success:
  - codecov

